name: Checkmarx CLI IaC Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkmarx-cli-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download Checkmarx CLI
        run: |
          curl -L -o cx.tar.gz https://github.com/Checkmarx/ast-cli/releases/download/2.3.48/ast-cli_linux_arm64.tar.gz
          tar -xzf cx.tar.gz
          chmod +x cx
          ./cx version

      - name: Authenticate to Checkmarx One
        run: |
          ./cx auth login \
            --cx-tenant cx_ind_internal_test \
            --base-uri https://ind.ast.checkmarx.net \
            --base-auth-uri https://ind.iam.checkmarx.net \
            --client-id rakshu \
            --client-secret ${{ secrets.CX_CLIENT_SECRET }}

      - name: Run IaC scan
        run: |
          ./cx scan create \
            --project-name "Rakshhh24/SCA" \
            -s . \
            -b main \
            --scan-types iac-security \
            --iac-security-platforms Terraform,Kubernetes \
            --iac-security-preset-id 5939486f-90a7-416d-91ea-d8e55a13334f \
            --debug
